Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,39 +15,25 @@ jobs:
           uses: actions/checkout@v4
           
         - name: Install Gitleaks
-          run: | 
-            curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz | tar -xz
-            mv gitleaks /usr/local/bin/
+          uses: zricethezav/gitleaks-action@v2
+          with:
+            config-path: .gitleaks.toml
+            report-path: secret-report.json
+            report-format: json
 
-        - name: Scan for Secrets
-          run:| 
-            gitleaks detect --source . --config .gitleaks.toml --report-format json --report-path secret-report.json || echo "Skipping failure"
+        - name: Upload Artifacts
+          uses: actions/upload-artifact@v4
+          with:
+           name: secret-report
+           path: secret-report.json
 
-
+        
         - name: Check for secrets
           run: |
             if [ -s secret-report.json ] && [ "$(jq '. | length' secret-report.json)" -gt 0 ]; then
-               echo "Secrets found in code. Logging results instead of aborting."
-               cat secret-report.json
-            else
-               echo "No secrets found, continuing..."
-            fi || echo "Skipping failure"
-
-          
-
-            
-        - name: Upload secret scan report
-          run: |
-            mkdir -p artifacts
-            mv secret-report.json artifacts/
-            tar -czf secret-report.tar.gz -C artifacts .
-            echo "ARTIFACT_PATH=secret-report.tar.gz" >> $GITHUB_ENV
-          
-        - name: Upload artifact
-          run: |
-            curl -s -u ${{ github.actor }}:${{ secrets.PAT_TOKEN }} \
-              -H "Accept: application/vnd.github.v3+json" \
-              -T ${{ env.ARTIFACT_PATH }} \
-              https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/tar.gz
-
+              echo "Secrets found in code. Aborting pipeline."
+              cat secret-report.json
+              exit 1
+            fi
+        
         
