ci.yml updated

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,16 +22,19 @@ jobs:
         - name: Run Gitleaks Scan
           run: |
             gitleaks detect --source . --config .gitleaks.toml --report-format json --report-path secret-report.json || true
-
-        - name: Upload secret scan report
-          run: |
             echo "ARTIFACT_PATH=secret-report.json" >> $GITHUB_ENV
-
-       
+          
         - name: Upload Gitleaks Report as tar.gz
           uses: actions/upload-artifact@v4
           with:
             name: gitleaks-report
             path: ${{ env.ARTIFACT_PATH }}
 
+        - name: Check for formats
+          run: |
+           if [ -s secret-report.json ] && [ "$(jq '. | length' secret-report.json)" -gt 0 ]; then
+              echo "Secrets found in code. Aborting pipeline."
+              cat secret-report.json
+              exit 1
+           fi
 
